# Generated by Django 5.2 on 2025-04-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_date_event_scheduled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField()),
                ('ticket_code', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(choices=[('GENERAL', 'GENERAL'), ('VIP', 'VIP')], max_length=10)),
            ],
        ),
    ]
