# Generated by Django 5.2 on 2025-04-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_refoundrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refoundrequest',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
