# Generated by Django 5.2 on 2025-04-24 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_event', to='app.category'),
            preserve_default=False,
        ),
    ]
