# Generated by Django 5.2 on 2025-04-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_notification_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('high', 'Alta'), ('normal', 'Normal'), ('low', 'Baja')], default='low', max_length=10),
        ),
    ]
