# Generated by Django 5.2 on 2025-04-30 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_refoundrequest_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='refoundrequest',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='refound_event', to='app.event'),
            preserve_default=False,
        ),
    ]
